name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CICD
    name: Test python API
    steps:
    - uses: actions/checkout@v1
    - name: Install requirements
      run: python3 -m pip install -r requirements.txt
    - name: Install local package
      run: python3 -m pip install -e .
    - name: Run tests and collect coverage
      run: python3 -m pytest --cov ./tests/
    - name: Upload coverage reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }}
